include:
- project: uniget-org/templates
  file: uniget.yaml
  ref: main

pages:
  extends:
  - .uniget-install
  image: python:3.13.0
  script:
  - |
    apt-get update
    apt-get -y install --no-install-recommends \
        bc \
        coreutils
  - |
    uniget install \
        hugo \
        regclient \
        gojq \
        go \
        gomplate
  - |
    git clone https://gitlab.com/uniget-org/tools uniget-tools
  - |
    cp -r uniget-tools/tools .
    cp uniget-tools/make/*.mk make
    rm -rf tools/dummy*
  - |
    make metadata.json
    mv metadata.json metadata.json.orig
    jq 'del(.tools[] | select(.name | startswith("dummy")))' metadata.json.orig >metadata.json
  - make site-prerequisites
  - |
    make -j$(nproc) pages
    make site
    mv site/public .
  artifacts:
    paths:
    - public