include:
- project: uniget-org/templates
  file: uniget.yaml
  ref: main

pages:
  extends:
  - .uniget-install
  image: python:3.13.0
  script:
  - |
    uniget install \
        hugo \
        regclient \
        gojq \
        go
  - |
    make metadata.json
  - |
    make site-prerequisites
  - |
    make -j4 pages
    make site
    mv site/public .
  artifacts:
    paths:
    - public