baseURL: https://docker-setup.dille.io
title: docker-setup
copyright: "Some copyright notice - [my license](https://example.com/license)"
theme:
- gitlab.com/gabmus/hugo-ficurinia
languageCode: en-us
paginate: 10

params:
  author: Nicholas Dille
  description: The container tools updater and installer
  logo: "/logo.svg"
  showSinglePageAsHome: true
  homeSinglePage: /browse
  showPostsLink: false
  extraContentDirs:
  - tools
  showTags: false
  showRss: false
  gridView: true
  navtype: standard
  infiniteScrolling: true
  paperCards: false

menu:
  main:
  - identifier: tags
    name: Tags
    url: /tags
    weight: 90
  - identifier: impressum
    name: Impressum
    url: /impressum
    weight: 100
  
taxonomies:
  tag: tags
  category: categories

outputs:
  home:
  - HTML
  - JSON